<?php
return [
'add' => 'Добавить',
'add_all' => 'Добавить все',
'delete' => 'Удалить',
'delete_all' => 'Удалить все',
'edit' => 'Изменить',
'insert' => 'Вставить',
'insert_all' => 'Вставить все',
'more' => 'Подробнее',
/*Pagination*/
'home' => '&laquo; В начало',
'end' => 'В конец &raquo;',
'previous' => '&larr; Назад',
'next'     => 'Вперед &rarr;'
'forward' => 'Вперед',
'back' => 'Назад',
/*Auth*/
'login' => 'Войти',
'logout' => 'Выйти',
'email' => 'E-mail',
'password' => 'Пароль',
'forgott' => 'Забыли пароль?',
'remember' => 'Запомнить меня',
/*Articles*/
'create' => 'Создать',
'create_multiple' => 'Создать несколько',
'clear' => 'Очистить',
'clear_all' => 'Очистить все',
'move' => 'Перенести',
'move_all' => 'Перенести все',
'move_from' => 'Перенести из',
'move_to' => 'Перенести в',
'copy' => 'Дублировать',
'copy_from' => 'Дублировать из',
'copy_to' => 'Копировать в',
'copy_all' => 'Копировать все',
'cancel' => 'Отменить',
'cancel_all' => 'Отменить все',
'select' => 'Выбрать',
'select_all' => 'Выбрать все',
'invert_selected' => 'Инвертировать вбранное',
'publish' => 'Опубликовать',
'unpublish' => 'Снять с публикации',
'trash' => 'В корзину',
'clear_trash' => 'Очистить корзину',
'restore_trash' => 'Восстановить корзину',
'restore_item_trash' => 'Убрать элемент с корзины',
'hard_delete' => 'Удалить навсегда',
'mark_delete' => 'Отметить на удаление',
'unmark_delete' => 'Снять отметку на удаление',
'mark' => 'Отметить',
'unmark' => 'Снять отметку',
'mark_all' => 'Отметить все',
'unmarl_all' => 'Снять все отметки',
'invert_mark' => 'Инвертировать отмеченное',
/*Search*/
'search' => 'Искать',
'smart_search' => 'Умный поиск',
'options' => 'Опции',
'advanced_options' => 'Расширенные опции',
'options_item' => 'Опции элемента',
'global_options' => 'Опции для всех элементов',
/*Settings*/
'settings' => 'Настройки',
'global_settings' => 'Общие настройки',
'advanced_settings' => 'Расширеные настройки',
/*Helpers*/
'help' => 'Справка',
'prompt' => 'Подсказка',
'status' => 'Состояние',
/*Import-Export*/
'import' => 'Импорт',
'import_from' => 'Импортировать из',
'import_to' => 'Импортировать в',
'export' => 'Экспорт',
'export_from' => 'Экспортировать из',
'export_to' => 'Экспортировать в',
/*Filter*/
'filter' => 'Фильтр',
'advanced_filter' => 'Рассширеный фильтр',
'reset_filter' => 'Очистить фильтр',
'reset' => 'Сбросить',
'reset_all' => 'Сбросить все',
/*Yes-No*/
'yes' => 'Да',
'no' => 'Нет',
/*Action*/
'new' => 'Новый',
'go_to' => 'Перейти к',
'go' => 'Перейти',
'update' => 'Сохранить изменения',
'update_all' => 'Сохранить все изменения',
'refresh' => 'Обновить',
'refresh_all' => 'Обновить все',
'apply' => 'Применить',
'apply_all' => 'Применить все',
'open' => 'Открыть',
'open_all' => 'Открыть все',
'close' => 'Закрыть',
'close_all' => 'Закрыть все',
'confirm' => 'Подтвердить',
'confirm_all' => 'Подтвердить все',
'save' => 'Сохранить',
'save_all' => 'Сохранить все',
'save_as' => 'Сохранить как',
'remove' => 'Убрать',
'remove_all' => 'Убрать все',
'preview' => 'Предпросмотр',
'view' => 'Вид',
'up' => 'Наверх',
'down' => 'Вниз',
/*Sort*/
'ascending' => 'По возрастанию',
'descending' => 'По убыванию',
/*History*/
'history' => 'История',
'item_history' => 'История элемента',

/*Tools*/
'tools' => 'Инструменты',
'advanced_tools' => 'Расширенные инструменты',
'position' => 'Позиция',
'rules' => 'Правила',
'rule' => 'Правило',
'context' => 'Контекст',
'order' => 'Порядок',
'action' => 'Действие',
'actions' => 'Действия',
'turn_left' => 'Повернуть влево',
'turn_rigtht' => 'Повернуть в право',
'custom' => 'Настроить',
'customize' => 'Личные настройки',
'page' => 'Страница',
'pages' => 'Страницы',
'event' => 'Событие',
'events' => 'События',
'changes' => 'Изменения',
'manage' => 'Управление',
'warnings' => 'Предупреждения',
'success' => 'Успех',
];
